# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20170717_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_aboutme',
            field=models.BooleanField(default=False, verbose_name=b'\xe5\x85\xb3\xe4\xba\x8e\xe8\x87\xaa\xe5\xb7\xb1'),
        ),
    ]
